name: Publish

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Get Version
        uses: kzrnm/get-net-sdk-project-versions-action@v1.3.0
        id: get-version
        run: | 
        LATEST_VERSION=$(cat ./oneware-package.json | jq -r '.versions | max_by(.version | split(".") | map(tonumber)) | .version')
        echo "Latest version is $LATEST_VERSION"
        echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
      - name: Compress
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: ../OneWare.TangNano9K_${{steps.get-version.outputs.version}}_all.zip
          directory: ./
          exclusions: '*.git* oneware-package.json'
      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "OneWare.TangNano9K_${{steps.get-version.outputs.version}}_all.zip"
          tag: ${{steps.get-version.outputs.version}}
          allowUpdates: true